apiVersion: v2
name: frontend-app
description: A comprehensive Helm chart for React frontend with service mesh and monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: istio-base
    version: "1.20.0"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
  - name: istiod
    version: "1.20.0"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled