{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.app.name }}-gateway
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . }}
    {{- end }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: {{ .Values.istio.gateway.tls.mode }}
      credentialName: {{ .Values.istio.gateway.tls.credentialName }}
    hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . }}
    {{- end }}
{{- end }}