{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-netpol
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  - from:
    {{- range .Values.networkPolicy.ingress.allowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ . }}
    {{- end }}
    - podSelector: {}
    ports:
    {{- range .Values.networkPolicy.ingress.allowedPorts }}
    - protocol: TCP
      port: {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
  - to:
    {{- range .Values.networkPolicy.egress.allowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ . }}
    {{- end }}
    ports:
    {{- range .Values.networkPolicy.egress.allowedPorts }}
    - protocol: TCP
      port: {{ . }}
    - protocol: UDP
      port: {{ . }}
    {{- end }}
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
    - protocol: UDP
      port: 53
  {{- end }}
{{- end }}